#!/usr/bin/bash
sudo pacman -S --needed xorg-server xorg-xinit libx11 libxinerama libxft terminus-font base-devel git tar kodi
cd $HOME/mrsystem/dwm
sudo make clean install
cd $HOME
printf 'kodi-standalone &\nexec dwm' > $HOME/.xinitrc
printf 'if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then\nstartx\nfi' >> $HOME/.bash_profile
sudo mkdir -p /etc/systemd/system/getty@tty1.service.d/
sudo mv $HOME/mrsystem/override.conf /etc/systemd/system/getty@tty1.service.d/override.conf
sudo mv $HOME/mrsystem/.kodi $HOME
sudo systemctl enable avahi-daemon.service
rm -rf $HOME/mrsystem
sudo reboot
