#!/usr/bin/bash
if [ ! -d $HOME/dwm-6.6 ] && echo 'download and extract dwm' && exit
cd $HOME
sudo pacman -S --needed xorg base-devel git tar kodi
git clone 'https://github.com/MrDraxs/mrsystem.git'
cd $HOME/dwm-6.6
rm $HOME/dwm-6.6/config.def.h
mv $HOME/mrsystem/dwn/config.def.h $HOME/dwm-6.6/config.def.h
sudo make clean install
cd $HOME 
printf 'kodi-standalone &\nexec dwm' > .xinitrc
printf 'if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then\nstartx\nfi' >> .bash_profile
sudo mv mrsystem/autologin@.service /etc/systemd/system/autologin@.service
ln -s /etc/systemd/system/autologin@.service /etc/systemd/system/getty.target.wants/getty@tty1.service
sudo systemctl daemon-reload
sudo systemctl start getty@tty1.service
#rm -rf $HOME/dwm-6.6
